import { Middleware, createAsyncThunk, createSlice } from "@reduxjs/toolkit";
import { youtubeApi } from "./youtubeApi";
import { RootState } from "../store";


export const fetchPlaylistsAfterAuth = createAsyncThunk(
  'youtube/fetchPlaylists',
  async (token, { dispatch }) => {
    // Assuming you're using a hook generated by createApi to initiate the query
    const result = await dispatch(youtubeApi.endpoints.getPlaylistVideos.initiate(token));
    // Handle the result of the query
    return result.data; // Or handle errors as needed
  }
);

export const youtubeSlice = createSlice({
  name: 'auth',
  initialState: {
    playlists: [],
    // other state properties
  },
  reducers: {
    // reducers here, e.g., setToken, etc.
  },
  extraReducers: (builder) => {
    builder.addCase(fetchPlaylistsAfterAuth.fulfilled, (state, action) => {
      // Update state with the fetched playlists
      console.log(action)
      state.playlists = action.payload;
    });
    // Handle other cases (pending, rejected) as needed
  },
});


export const playlistsMiddleware: any = (store) => (next) => (action: any) => {
  // Adjust the action type check according to your actual implementation
  const result = next(action);

  if (action.type === 'auth/setAuthToken') {
    const newState = store.getState();
    // Dispatch the `getPlaylists` endpoint call using the RTK Query API
    console.log('dispatching getPlaylists')
    console.log(newState);
    console.log(action.payload);


    store.dispatch(youtubeApi.endpoints.getPlaylists.initiate(null) as any);
  }

  return next(action);
};